markdown: GFM
title: "GOLD: the Gawk object layer"
highlighter: rouge
remote_theme: pmarsceill/just-the-docs

footer_content: "Copyright &copy; 2020 Tim Menzies, <a href=\"http://github.com/timm/gold/tree/master/LICENSE.md\">MIT License</a>"

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/timm/gold" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

