reload() {
  rm $Sh/.var/*rc
  sh $Sh/gold.sh --install
  . $Sh/.var/bashrc
}


alias awk="gold --all; AWKPATH='$Sh/.var:$AWKPATH'  gawk -f $Sh/.var/gold.awk "
alias gold="bash $Sh/gold.sh "
alias gg="git pull"   
alias gs="git status"   
alias gp="git commit -am 'saving'; git push; git status"    

matrix() { nice -20 cmatrix -b -C cyan;   }
vims()   { vim -u $Sh/.var/vimrc +PluginInstall +qall; }

alias vi="vim    -u $Sh/.var/vimrc"
alias tmux="tmux -f $Sh/.var/tmuxrc"

here()  { cd $1; basename `pwd`; }    

PROMPT_COMMAND='echo -ne "🔆 79º $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'     
